### ISSUE TITLE
Maven publish artifacts don't retain .cfn.jar filename

### ISSUE THREAD

**Issue by spohnan** [cfn-stacks/artifacts3-repo#5]
As it only makes sense to unzip CloudFormation script jars we need to restrict the Lambda function to only run for .cfn.jar files. The local artifact has the correct extension but the ones going through the maven-publish plugin only have .jar

```
LambdaConfigurations:
          - Function: !GetAtt UnzipArtifactsFunction.Arn
            Event: 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: '.jar'
                    #Value: '.cfn.jar'
```
